### PR TITLE
Points updated and some small corrections.

### PR DESCRIPTION
**Pull request by rammurat**

### CODE REVIEW

**Review by Mayank02 — COMMENTED** [review]
Thanks, Ram for point out these changes but with your changes you have changed the structure of the JSON that will break the code. You might want to try to take a pull and see the changes

**Comment by rammurat** [comment]
This must be my Smart VS Code :( Corrected the PR. Thanks Mayank.

**Review by Mayank02 — COMMENTED** [review]
@rammurat Check the Non-function section of JSON. It's an object.

**Comment by Mayank02** [comment]
I have made the required changes and merging this to master

**Pull request merged**
